name: test workflow

on:
  push:
    branches:
      - master

jobs:
    integration:
        runs-on: ubuntu-latest

        steps: 
            - name: Test workflow
              run: echo "Test this workflow"